version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80" 

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3005:3005"  